language: c
dist: trusty
sudo: required

before_install:
  #- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  #- sudo apt-get -qq update
  #- sudo apt-get install libc6-dev-i386 gcc-5-multilib g++-5-multilib
  #- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - sudo apt-get install gcc-multilib g++-multilib gcc-arm-none-eabi libnewlib-arm-none-eabi
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - git clone https://github.com/apache/mynewt-newt
  - cd mynewt-newt && ./build.sh && cd ..
  # FIXME: project.yml was changed to add remote dep (yes, srsly!)
  - mynewt-newt/newt/newt install -v
  - mynewt-newt/newt/newt target create bletiny_nrf52840_coverity
  - mynewt-newt/newt/newt target set bletiny_nrf52840_coverity app=@apache-mynewt-core/apps/bletiny
  - mynewt-newt/newt/newt target set bletiny_nrf52840_coverity bsp=@apache-mynewt-core/hw/bsp/nrf52840pdk
  - mynewt-newt/newt/newt target set bletiny_nrf52840_coverity build_profile=debug
  - mynewt-newt/newt/newt target set bletiny_nrf52840_coverity syscfg=BLE_SM_LEGACY=1:BLE_SM_SC=1:BLE_EDDYSTONE=1:BLE_EXT_ADV=1:BLE_EXT_ADV_MAX_SIZE=50:BLE_MULTI_ADV_INSTANCES=2:BLE_LL_CFG_FEAT_LE_2M_PHY=1:BLE_LL_CFG_FEAT_LE_CODED_PHY=1:BLE_SM_BONDING=1:BLE_L2CAP_COC_MAX_NUM=2:BLE_HS_DEBUG=1:LOG_LEVEL=0

script: ""

env:
  global:
    - secure: "CN2ky7nTp9xxr2gMQI1mF8ZA+oBEAaasgm/9wijYu1m2tVUqLqoLsh4f60/h+mZzFHeVDDlT4+aEfLQguDufoS05p30fRPqaBMNSzVJxHhpoy5qR7bSEpHL4fvNkmdJ//8o57z1NCR8O5R/m5kE//Rc/4eprwopIRl4tIliD9P84A9GzX62IrSbCRa3LMQdp93KA1t8xiX+w/oAoQEdFz1PjRNoGyXmqP80TWsY+1x6xZjEBXDArYMhSrpj0Bo38SSqdRFayg5PcNOa2zKsoyuLV1tXFhVEuvEvXlb6ruLy0m2HLG24vWYaJ7DeyfGb/Qzb9r+TxfXE/plp2n9Bq7b5x1idWxFpV1gvuks2bEOlaBm9z8a9QpE+zq3rFAFinb0N0pNCnJQVYHIbdOGxvXYhQNVE2ze8HAQZv0vsVP35JB8qUttfUdaTyUGyT7rpYZyiN4/AK0VI6Qum2DovXRf0gdwzPDGq5uBpkJ8QwDyA9Q1LfKC0l2CqS+x+2Pd2l8AtS1LFxN7nvLu3vljA0llayEvxeJjvLu/2sGHk0MNAdN03e/mkNSqF1wyOy3aWOm74ctQgzmXbNHWhsW3nrto1kQqc+BtXJINFGPw0kJkUDHnqCQSg2PL+LApLf0+etK6QQg59HmqGfLMpB0HaUMd/JR/OQUia0flftQL+mmSY="

addons:
  coverity_scan:
    project:
      name: "apache/mynewt-core"
      version: 1.3.0
      description: "An OS to build, deploy and securely manage billions of devices"
    notification_email: utzig@apache.org
    build_command_prepend: "cov-configure --comptype gcc --compiler /usr/bin/arm-none-eabi-gcc"
    build_command: "cov-build --dir cov-int mynewt-newt/newt/newt build --executeShell bletiny_nrf52840_coverity"
    branch_pattern: "coverity_scan"
